# Generated by Django 6.0 on 2026-01-10 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_paymentmethod_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='example',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('paragraph', models.TextField()),
                ('product_name', models.CharField(max_length=100)),
                ('example_2', models.CharField(max_length=100)),
                ('example_1', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
