# Generated by Django 6.0 on 2026-04-13 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_product_product_img_remove_product_sku_skill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_low_stock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='reorder_level',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_alerts', to='api.business')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_alerts', to='api.product')),
            ],
            options={
                'unique_together': {('product', 'is_resolved')},
            },
        ),
    ]
