# Generated by Django 6.0 on 2026-04-21 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_delete_usersettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='AprioriRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antecedent', models.CharField(max_length=255)),
                ('consequent', models.CharField(max_length=255)),
                ('support', models.FloatField()),
                ('confidence', models.FloatField()),
                ('lift', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apriori_rules', to='api.business')),
            ],
            options={
                'unique_together': {('business_id', 'antecedent', 'consequent')},
            },
        ),
    ]
