# Generated by Django 6.0 on 2026-04-22 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_business_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
    ]
