# Generated by Django 6.0 on 2026-04-25 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_remove_employee_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
        migrations.AlterField(
            model_name='counter',
            name='counter_number',
            field=models.IntegerField(unique=True),
        ),
    ]
