# Generated by Django 6.0 on 2026-04-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_product_cost_price_product_product_img_product_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='transaction_type',
            field=models.CharField(default='Sales', max_length=20),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='skill',
            unique_together={('name', 'business_id')},
        ),
    ]
