# Generated by Django 6.0 on 2026-05-15 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_expense_expense_number_expense_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stockalert',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='stockalert',
            constraint=models.UniqueConstraint(condition=models.Q(('is_resolved', False)), fields=('product',), name='unique_unresolved_stockalert_per_product'),
        ),
    ]
