# Generated by Django 6.0 on 2026-05-18 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_add_dashboard_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='billing',
            new_name='api_billing_busines_447b6c_idx',
            old_name='api_billing_busine_4d2c8d_idx',
        ),
        migrations.RenameIndex(
            model_name='party',
            new_name='api_party_busines_fcae83_idx',
            old_name='api_party_busines_3f9ea2_idx',
        ),
        migrations.RenameIndex(
            model_name='reminder',
            new_name='api_reminde_busines_f18355_idx',
            old_name='api_reminder_busine_1c98d2_idx',
        ),
    ]
