# Generated by Django 5.2.13 on 2026-05-07 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderCart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercart',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
