# Generated by Django 5.2.13 on 2026-05-12 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderCart', '0002_alter_ordercart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercart',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
